### ISSUE TITLE
Social Media links on Website

### ISSUE THREAD

**Issue by csengep** [DashboardHub/PipelineDashboard#1022]
Add: 

- Facebook, Twitter, Instagram and LinkedIn for DH 
- YouTube channel of Eddie, any other social media you want

**Comment by eddiejaoude** [comment]
Is this now done? Or is it meant for the app also?

<img width="810" alt="screenshot 2018-10-13 01 37 06" src="https://user-images.githubusercontent.com/624760/46896963-97a75480-ce88-11e8-8c1f-ab10cf96b8f6.png">

**Comment by csengep** [comment]
I think thats done, didn't mean the app.

**Comment by eddiejaoude** [comment]
thanks. 👍
