### ISSUE TITLE
Pull Requests over 5 days old goes RED

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#103]

**Comment by brettminnie** [comment]
:+1: an aging feature like this is great. Possibly at a later stage we can automate reminders to the assignee

**Comment by eddiejaoude** [comment]
Thanks :).

> ...automate reminders to the assignee... 

Nice idea :+1: . I will add it to the backlog

**Comment by eddiejaoude** [comment]
Created https://github.com/DashboardHub/PipelineDashboard/issues/104
