### ISSUE TITLE
LinkedIn page - Showcase or Company? 

### ISSUE THREAD

**Issue by csengep** [DashboardHub/PipelineDashboard#1048]
- DH LinkedIn page is currently a Showcase which can do its own posts, comments and general interactions 

**Benefits of Company Page:** 
- I think that overall it just looks more professional and interactive, it literally is a company instead of a project
- Showcase pages are for promoting specific parts of a business to a very targeted market
- Eventually DashboardHub would have to probably become a Company Page anyway so probably better to do it pre-websummit - we look more serious 

https://www.venturestream.co.uk/blog/benefits-company-showcase-pages-linkedin/

https://business.linkedin.com/en-uk/marketing-solutions/blog/posts/marketing-solutions/2017/LinkedIn-Company-Pages-and-LinkedIn-Showcase-Pages-your-questions-answered

**Comment by eddiejaoude** [comment]
I will close this ticket as it was for the research part. I have created #1061 to do the conversion to a company.
