### ISSUE TITLE
Eddie LinkedIn

### ISSUE THREAD

**Issue by csengep** [DashboardHub/PipelineDashboard#1049]
- Biography/summary needs to be shortened 
- More concise 

Can we put most of the information on your website and put the link in there?

**Comment by csengep** [comment]
ONLY interested in CONTRACT work, please contact via EMAIL and include the following useful information: location, duration, skills / technologies, rate.

GitHub: https://github.com/eddiejaoude
YouTube: http://youtube.com/eddiejaoude?sub_confirmation=1

Fullstack polygot. Open Source & Best Practice advocate. Passionate for #diversity & #inclusion in tech. Support many tech for good communities.

_Eddie strives continually to improve his technical skills by maintaining and contributing to many Open Source projects on GitHub. Leading by example, Eddie’s core skills are in Architecture, Development, DevOPs and Automated Testing (TDD & BDD), with these skills he is able to implement Continuous Integration and Continuous Deployment at the start of the project, thus reducing the feedback loop for every change and allows proactive improvements by the Agile team._ 
^this bit is a reference, whoever wrote it you should ask to post it to your page as a reference and should be cut from your bio 

Highly active on GitHub with contributing to many Open Source projects https://github.com/eddiejaoude and speaks at various conference around the world on Best Practices. Also in 2015 in the top 500 Open Source Contributors on GitHub in the world and in 2016 trended in the top 11 with organisations like Mozilla, Twitter, Angular and Microsoft.

_Worked in the public and private sectors including: Ministry of Justice, HMRC, Crossrail, FinTech._
^this bit should be in your work experience, I do not think it needs to be in your bio. 

CV & references available on request.

**Comment by csengep** [comment]
Draft 1: 

Having worked as a Senior Software Consultant over the last 13 years, I have contributed to many Open Source projects on GitHub, and I am an Open Source and Best Practice Advocate, speaking at conferences around the world promoting these. I am also passionate for diversity and inclusion in tech and support a number of good communities. 

Please note that I am only interested in contract work, and should you have an opportunity please contact me vie e-mail including the following useful information: location, duration, skills/technologies, rate.

**Comment by eddiejaoude** [comment]
Updated 👍

**Comment by eddiejaoude** [comment]
@csengep assigned to you for review, thanks
