### ISSUE TITLE
FOSDEM form response

### ISSUE THREAD

**Issue by csengep** [DashboardHub/PipelineDashboard#1065]
**Description of project(s) for publication:**

DashboardHub gives a no set-up solution to inefficiency and miscommunication in your software deployment pipeline, caused by slow relay of information about new version releases in each environment. By providing a platform for internal and external team members, we provide an easy monitoring system, with detail and a comprehensive overview. The dashboard clearly shows the stage at which the continuous deployment is running and completed, in stages like development, test and production environments and anything in between, with the version on which they are currently hosting. The performance of each version is also shown through trend build and deployment metrics. What makes DashboardHub truly unique is that the platform keeps up with frequent releases, removing the increased miscommunication.

**Why does it fit FOSDEM?**

The project is fully open source, all our code, meeting notes and retrospectives can be found on GitHub. Our team is working fully remotely and flexibly to give us the most diverse and inclusive team possible, in line with our values of equal opportunity, inclusivity and transparency.

**Comment by eddiejaoude** [comment]
Thanks, applied 👍
