### ISSUE TITLE
UI tweaks for Angular v7

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1068]
<img width="1497" alt="screenshot 2018-11-01 08 21 17" src="https://user-images.githubusercontent.com/624760/47841747-9051d780-ddb2-11e8-967a-11d8065df91e.png">

<img width="1496" alt="screenshot 2018-11-01 08 22 33" src="https://user-images.githubusercontent.com/624760/47841764-98117c00-ddb2-11e8-9ab0-45f54af9ab0c.png">

<img width="1498" alt="screenshot 2018-11-01 08 22 49" src="https://user-images.githubusercontent.com/624760/47841774-9e9ff380-ddb2-11e8-89ed-ad31132a7462.png">

**Comment by tanyapowell** [comment]
TAG! I'm it. Will fix it today 😄
