### ISSUE TITLE
Add placeholder or example to Description when creating an enivironment

### ISSUE THREAD

**Issue by tanyapowell** [DashboardHub/PipelineDashboard#1071]
### Requirements
Hello 👋, would be great if there's a placeholder/example in the description field when creating an environment.

Not sure if I'm meant to add the type of environment here, e.g. dev or staging or prod, or something else
![image](https://user-images.githubusercontent.com/11095605/48008342-63cef000-e111-11e8-8b9e-6098acfd5a89.png)

**Comment by eddiejaoude** [comment]
Good idea 👍

**Comment by eddiejaoude** [comment]
Closing as environments are no longer created, viewing from the project and repo direction.
