### ISSUE TITLE
Add Roadmap to documentation repo

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1077]
Similar to these examples https://twitter.com/geekygirldawn/status/1062373551003590657 

- https://github.com/drud/ddev/wiki/roadmap
- https://www.habitat.sh/community/
- https://github.com/strapi/strapi/projects/1

**Comment by eddiejaoude** [comment]
Could use AsciiDoctor diagrams, for example http://blockdiag.com/en/nwdiag/nwdiag-examples.html

**Comment by eddiejaoude** [comment]
Road map

| version | date | title | description |
| :--- | :--- | :--- | :--- |
| v0.11.5 | 31st May 2019 | AWS to Firebase | realtime dashboard updates |
| v0.11.6 | 31st June 2019 | Monitoring | monitor all your deploy environments |
| v0.11.9 | 14th Sept 2019 | Web Engineering | DashboardHub supporting Weuceu |

**Comment by csengep** [comment]
![Image from iOS (2)](https://user-images.githubusercontent.com/38459876/57647491-fff31b80-75ba-11e9-9c9b-1a0a0ddc241b.jpg)

- aimed for a flow chart look 
- version, date and title included 
- more details available as you click on the boxes

**Comment by eddiejaoude** [comment]
Another option is something like this, but without the cloud, what do you think? http://blockdiag.com/en/nwdiag/nwdiag-examples.html#peer-networks

**Comment by eddiejaoude** [comment]
I had a quick play with `blockdiag` and it seems a bit of a pain, better to stick with `mermaid` 👍

**Comment by csengep** [comment]
https://mermaidjs.github.io/flowchart.html
https://mermaidjs.github.io/gantt.html 

I think one of these two would be appropriate, any preferences?

**Comment by eddiejaoude** [comment]
I really prefer the Gant chart (especially the 2nd one with the extra text). I can also help if you need too 🤓

**Comment by csengep** [comment]
```
gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d
```


![Screen Shot 2019-05-18 at 11 39 17](https://user-images.githubusercontent.com/38459876/57968374-99c31b80-7961-11e9-9210-a9bf4e6d26a7.png)

**Comment by eddiejaoude** [comment]
Looks great 👍

**Comment by eddiejaoude** [comment]
I am going to leave in review until we add to the documentation repo - I think you will need my input on dates first though

**Comment by eddiejaoude** [comment]
With real data:

```mermaid
gantt
    title DashboardHub RoadMap 2019
    dateFormat DD-MM-YY

    section Version 11.6
    Monitors :active, monitors, 20d

    section Version 11.7
    Webhooks :crit, webhooks, 30d
    Deployments :deployments, after monitors, 10d

    section Version 11.8
    Project dashboard :dashboard, after deployments, 10d
```

<img width="1942" alt="Screenshot 2019-06-30 08 04 33" src="https://user-images.githubusercontent.com/624760/60393460-bb412680-9b0d-11e9-8933-3faab13079da.png">
