### ISSUE TITLE
Homepage & README screenshots of Desktop / Tablet / Mobile

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#109]
E.g. http://www.nitinh.com/wp-content/uploads/2013/03/what-is-responsive-web-design-700x466.png 

![what-is-responsive-web-design-700x466](https://cloud.githubusercontent.com/assets/624760/6769398/61ddb8f6-d091-11e4-967f-0e1adbbc7432.png)

**Comment by eddiejaoude** [comment]
<img width="1010" alt="screenshot 2016-08-16 19 47 25" src="https://cloud.githubusercontent.com/assets/624760/17733187/5488245e-646d-11e6-8f93-c05ca2b8a51c.png">

**Comment by brettminnie** [comment]
:+1::skin-tone-6:

Showing off :D

**Comment by eddiejaoude** [comment]
😛 ... I can't show off until it is deployed

**Comment by brettminnie** [comment]
deployed yes
