### ISSUE TITLE
Ideas for widgets

### ISSUE THREAD

**Issue by chris-moreton** [DashboardHub/PipelineDashboard#11]
Code quality
Coverage, test results, mutation test results, codesniffer, mess detector, duplicate code analysis, repo size etc...

Performance
Build time, load tests, speed tests - maybe with graphs over time

Service availability and health
Dev, UAT, prod, etc... versions, last deploy time, key data metrics (e.g. new users in last 24 hours), W3C HTML metrics perhaps, application log snippets, database size, backup status, disk space and memory status

Workflow
Outstanding issues, latest commits, pull requests

Feedback
Support tickets, outstanding/answered/closed, etc...

**Comment by eddiejaoude** [comment]
Some good ones in there! 

Can you prioritise them? approximately, may be into groups - high / medium / low

**Comment by eddiejaoude** [comment]
A few more sources for widgets...

* Jira
* Gitter 
   * how many people in chat room
   * last activity (eg. 10minutes ago)
* Slack
* Packagist (someone already mentioned)
* Version (someone already mentioned)
* Pingdom

**Comment by nicely-toasted** [comment]
some more widget ideas:

- bamboo, jenkins, parallelci
- artifactory, nexus
- gitlab, stash, bitbucket
- hipchat

**Comment by randompixel** [comment]
The most useful dashboard for me is Sonarqube. The time machine feature lets me see trends over time in code & build quality.

**Comment by eddiejaoude** [comment]
Data comparison with other Dashboards (e.g. activity, code coverage, popularity star/forks)

**Comment by eddiejaoude** [comment]
Gitter integration ( api: https://developer.gitter.im/docs/welcome )
* Channels available
* Users in each channel
* Last activity in channel

**Comment by nicely-toasted** [comment]
stimbled across this handy list of testing/CI related tools. Most probably have APIs we could integrate with ...

http://www.onextrapixel.com/2015/03/25/basics-of-extreme-programming-xp-a-list-of-free-continuous-integration-ci-tools/

**Comment by eddiejaoude** [comment]
@nicely-toasted There are quite a few on there I wasn't aware of. Thanks!

**Comment by brettminnie** [comment]
Magnum ci ftw

**Comment by eddiejaoude** [comment]
Possible building blocks for a dashboard https://github.com/keen/dashboards
