### ISSUE TITLE
curl commands should omit -X

### ISSUE THREAD

**Issue by dfandrich** [DashboardHub/PipelineDashboard#1131]
The curl commands should omit -X unless it is required (hint: it's almost never required). -X changes the way curl handles a request in subtle ways that can break requests in some cases. For regular posts (using e.g., -d or -F) -X is completely redundant. See also https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/

**Comment by eddiejaoude** [comment]
Thank you for the tip 👍

**Comment by eddiejaoude** [comment]
As moving away from using curl, this is no longer required.
