### ISSUE TITLE
Fosdem blog post

### ISSUE THREAD

**Issue by csengep** [DashboardHub/PipelineDashboard#1134]
- expectations pre-Fosdem 
- how we prepared 
- what Fosdem was like 
- takeaways

**Comment by csengep** [comment]
What did you do on the tech side to prepare for Fosdem on the tech side?

**Comment by eddiejaoude** [comment]
- Moving to Firebase for realtime data updates (using Firestore) especially when hooking into GitHub's WebHooks
- Firebase ecosystem is much more mature and not only has S3 like file storage but also machine learning (ML)
-
