### ISSUE TITLE
Issue template for bug / feature etc

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1150]
https://github.com/angular/material2/tree/master/.github/ISSUE_TEMPLATE

**Comment by richardhooper** [comment]
I'm taking a look at this as a Good First Issue!

Is the core of the issue just to set up templates for PipelineDashboard that broadly correspond to the Angular ones linked, but tweaked to more directly match PD's context?  I feel like they probably don't have to be to complex at this stage, but something is better than nothing!

A quick review of existing issues in this repo doesn't throw up any particular pattern, beyond something simple a bit like this: https://github.com/DashboardHub/PipelineDashboard/issues/1540

One other stumbling block: [GitHub currently recommend](https://help.github.com/en/articles/about-issue-and-pull-request-templates) that these templates are created via the relatively new "issue template builder", which is in Settings.  You can still edit the .md files directly I think, I'm happy to have a go that way.

**Comment by eddiejaoude** [comment]
Thanks for taking a look at this @richardhooper ! 

At the moment, we have a very simple single (too simple) template for issues, anything would be an improvement - yep you are right, we don't need anything complex

Coming to the project fresh, I trust your opinion on this 🤓
