### ISSUE TITLE
Review angular code

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1151]
Get familiar with the current project that is moving from AWS to Firebase. The current work is in this branch [firebase-mvp](https://github.com/DashboardHub/PipelineDashboard/tree/firebase-mvp)

Please list all review notes / feedback in a comment below (keep editing the same comment until complete).

Any questions add a new comment below 🤓

**Comment by eddiejaoude** [comment]
- authentication code LINK could be made more secure
-

**Comment by webkhushboo** [comment]
@eddiejaoude  I have few questions regarding the angular code .
Do you want me to review the proper structure , naming conventions and standard guidelines for code too ?

**Comment by eddiejaoude** [comment]
@webkhushboo can you give me an example of what you mean?

**Comment by webkhushboo** [comment]
@eddiejaoude 
Modules , components structure means all related components to dashboard should come under dashboard module. Right now I am seing folder for each components , not able to identify which components are part of which module and which are shared ?

**Comment by eddiejaoude** [comment]
Yes make notes on these too please 👍

**Comment by webkhushboo** [comment]
I follow one Angular code checklist for reviewing my code. Can I share with you so that you can have a look on it

**Comment by eddiejaoude** [comment]
Sure 👍

**Comment by webkhushboo** [comment]
[Angular_Code_Review_Checklist.xlsx](https://github.com/DashboardHub/PipelineDashboard/files/3090991/Angular_Code_Review_Checklist.xlsx)

Please find the attached checklist for your reference. I will follow the same

**Comment by eddiejaoude** [comment]
It looks good. If we can keep as much to Angular recommendations as possible, that would be perfect 👍 .

**Comment by webkhushboo** [comment]
Sure !! This was created based upon angular recommendations only.

**Comment by webkhushboo** [comment]
Reviews for Angular Code : 
1. Guards , interceptors, models, pipes, interceptors should fall under app folder based upon their modules.
2. Singleton services should go under core module. 
3. Lazy loading should be applied by putting all related components in a module and loaded them via routing
4. Shared components between modules should go under shared module and should be imported in feature modules
5. Core module should be imported into the app module
6. Naming for main component directly placed under app should be like app.component.html instead main.component.html as per standard naming guidelines for angular
7.  App routing module should be renamed to app-routing.module.ts and routing module should be added to each feature module
8. material.module.ts should be renamed to app-material.module.ts as per standard guidelines
9. import inside module should be grouped between core modules , app modules and app components and in alphabetical order
10. What is the use of main.component.ts if its not get referred any where in code.

Review is in progress will update continuously. Please let me know if you have any questions

**Comment by eddiejaoude** [comment]
This looks great 👍 .

Note: I split this issue into 3 (from the tasks that were in the description above)

- #1151 Review angular code
- #1152 Review firebase code
- #1153 Review UI functionality

**Comment by webkhushboo** [comment]
Sure !! Will do

**Comment by eddiejaoude** [comment]
Creating issues for each item

> 1. Guards , interceptors, models, pipes, interceptors should fall under app folder based upon their modules

#1158 

> 2. Singleton services should go under core module

#1159 

> 3. Lazy loading should be applied by putting all related components in a module and loaded them via routing

#1160

> 4. Shared components between modules should go under shared module and should be imported in feature modules



> 5. Core module should be imported into the app module



> 6. Naming for main component directly placed under app should be like app.component.html instead main.component.html as per standard naming guidelines for angular



> 7. App routing module should be renamed from routes.module.ts to app-routing.module.ts and routing module should be added to each feature module



> 8. material.module.ts should be renamed to app-material.module.ts as per standard guidelines



> 9. import inside module should be grouped between core modules , app modules and app components and in alphabetical order



> 10. What is the use of main.component.ts if its not get referred any where in code.



> 11. Proper one line comments should be added for imports grouping and function definitions in ts file



> 12. Proper formatting should be done for ts file



> 13. Remove ununsed `styles.css` as we are using `styles.scss`



> 14. Custom theme should be added in separate file



> 15. Providers for interceptors should be added to the module file instead interceptor providers: 
> ```
> [
>     {
>        provide: HTTP_INTERCEPTORS,
>        useClass: ErrorHttpInterceptor,
>       multi: true
>     }
> ]
> ```



> 16. Methods should be declared in alphabetical order in ts file for e.g (authentication.service.ts file ). Proper formatting and comments should be added into it



> 17. App Material module should contain declarations and exports for only material component . There is no use of Flex-layout module import in this module. So remove import from here and app import of flex-layout to app module



>     import { FlexLayoutModule } from '@angular/flex-layout';



> 18. Routes declaration should not be done inside main.component.ts file



> 19. Remove unused authentication service injection in main.component.ts file
>     public authService: AuthenticationService



> 20. Create _variable.scss file for declaring common font family and color code and other common things that needs to be reuse through out the app (Suggestion)



> 21. What is the purpose for charts module ? As of now there is no reference of chart used in the application.



> 22. Reusable component should be created for public projects and private projects under shared components



> 23. Create and edit should be created as reusable components under shared components



> 24. directives should be created under respected feature modules or if used between multiple modules then should be created as part of shared modules



> 25. environments folder under app folder is empty . so should be removed.

**Comment by eddiejaoude** [comment]
Smaller issues have been created from this one
