### ISSUE TITLE
Review firebase code

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1152]
Get familiar with the current project that is moving from AWS to Firebase. The current work is in this branch [firebase-mvp](https://github.com/DashboardHub/PipelineDashboard/tree/firebase-mvp)

Please list all review notes / feedback in a comment below (keep editing the same comment until complete).

Any questions add a new comment below 🤓

**Comment by webkhushboo** [comment]
Review comments on firebase code : 
1. Proper comments and formatting should be done in firebase functions index.ts file
2. Error handling is missing from authentication.service.ts file for login and logout functions
3. Formatting and comment should be added to authentication service, projects service , repository service and user service file as well .
4. Removed the unused service injection of authentication service in user service.

Review is still in progress , will update once done
