### ISSUE TITLE
Review UI functionality

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1153]
Get familiar with the current project that is moving from AWS to Firebase. The current work is in this branch [firebase-mvp](https://github.com/DashboardHub/PipelineDashboard/tree/firebase-mvp)

Please list all review notes / feedback in a comment below (keep editing the same comment until complete).

Any questions add a new comment below 🤓

**Comment by webkhushboo** [comment]
Review comments on UI functionality
1. As soon as user logs in Welcome guest should be changed to logout icon. Currently it changes to logout icon once user clicks somewhere in the application.
2. When click on signout from profile menu , it should redirect to home screen.For e.g  Currently if I am on privacy page and then I have click on sign out from sidebar , it keeps me on privacy page although it works perfectly when I click on logout button.

**Comment by eddiejaoude** [comment]
@webkhushboo looks great 👍

**Comment by eddiejaoude** [comment]
> 1. As soon as user logs in Welcome guest should be changed to logout icon. Currently it changes to logout icon once user clicks somewhere in the application.

Created ticket #1156 

> 2. When click on signout from profile menu , it should redirect to home screen.For e.g Currently if I am on privacy page and then I have click on sign out from sidebar , it keeps me on privacy page although it works perfectly when I click on logout button.

Created ticket #1157
