### ISSUE TITLE
Research into using The Dots for DashboardHub

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1155]
Similar to linkedin but project based...

https://the-dots.com

Interested to know benefits of using it and what updates is required

**Comment by csengep** [comment]
I think the worst case scenario is that we don‘t get anything out of it but thats already the case with LinkedIn so I definitely think it is worth joining. 

- ask the community feature would be really great for things like voting on a mascot or asking for recommendations and ideas 
- seems to be a more concentrated target audience at this stage, more likely to get testers and constructive feedback 
- they seem to put on events which could be a great networking opportunity
- project showcase features 
- not sure what you mean by updates required?

**Comment by eddiejaoude** [comment]
> not sure what you mean by updates required?

Me neither 🤦‍♂ 

Ok sounds great! When you are happy with the research we can close this ticket and raise a new one to actually post it on The Dots after the next release (probably July)
