### ISSUE TITLE
After logout redirect user to homepage

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1157]
> When click on signout from profile menu , it should redirect to home screen.For e.g Currently if I am on privacy page and then I have click on sign out from sidebar , it keeps me on privacy page although it works perfectly when I click on logout button.

From #1153

**Comment by webkhushboo** [comment]
@eddiejaoude 
Fixed as part of issue-1187 branch

Kindly review

**Comment by eddiejaoude** [comment]
@webkhushboo sure, which pull request?
