### ISSUE TITLE
Guards , interceptors, models, pipes, interceptors should fall under app folder

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1158]
> Guards , interceptors, models, pipes, interceptors should fall under app folder based upon their modules

From #1151

**Comment by webkhushboo** [comment]
@eddiejaoude 
gurads , interceptors are added to core module
pipes is all together different module and placed it inside app folder
models are created as part of shared module

This is implemented as part of issue #1160 
Kindly review and close it
