### ISSUE TITLE
Lazy loading should be applied by putting all related components in a module and loaded them via routing

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1160]
> Lazy loading should be applied by putting all related components in a module and loaded them via routing

From #1151

**Comment by eddiejaoude** [comment]
- main (homepage, privacy, legal ...)
- project (crud ..., add repo, ...)
- shared (pipes ...) - where required
- core (singleton, guards, interceptors) - always

**Comment by webkhushboo** [comment]
@eddiejaoude 

Main module and projects modules are created with respected components.
Modules are lazy loaded via routing in app-routing.component.ts

Kindly review and close it
