### ISSUE TITLE
Naming for main component directly placed under app

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1163]
> Naming for main component directly placed under app should be like app.component.html instead main.component.html as per standard naming guidelines for angular

From #1151

**Comment by webkhushboo** [comment]
@eddiejaoude 

1. main component content which is common to both main module and project module is moved to app component. (main.component.html --> app.component.html , main.component.ts --> app.component.ts, main.component.scss --> app.component.scss)
2. main component is updated as a entry point for main module.

Its implemented as part of issue #1160. Kindly review and confirm
