### ISSUE TITLE
Providers for interceptors should be added to the module

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1172]
> Providers for interceptors should be added to the module file instead interceptor providers: 
> ```
> [
>     {
>        provide: HTTP_INTERCEPTORS,
>        useClass: ErrorHttpInterceptor,
>       multi: true
>     }
> ]
> ```

From #1151

**Comment by webkhushboo** [comment]
Added interceptors to the core module as part of #1160. So we are just importing them in core module. No need to add providers in app module so closing it
