### ISSUE TITLE
environments folder under app folder is empty . so should be removed.

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1186]
> environments folder under app folder is empty . so should be removed.

From #1151 

I couldn't see this folder but created the issue to double check

**Comment by webkhushboo** [comment]
Closing this issue after double check for environment folder as its not present under app folder. In the begining when switched from master branch to firebase-mvp that time I might have seen that empty folder. Now its not showing in firebase-mvp branch so closing it.

**Comment by eddiejaoude** [comment]
👍
