### ISSUE TITLE
Update web dependencies

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1200]
Update all web dependencies including Angular to the [latest version](https://angular.io/guide/releases#release-schedule), probably version 8 by now

**Comment by webkhushboo** [comment]
We need to update node js version to 12 for updating angular version 7 to 8. Do you want to update to angular 8?

**Comment by eddiejaoude** [comment]
Let’s keep the node version the same and update as much as possible

**Comment by webkhushboo** [comment]
okay great
