### ISSUE TITLE
Add loading spinner to all http requests

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1223]
Similar to when logging in and load public projects

Areas...

- [x] Public projects list (done as part of #1204)
- [x] My projects list
- [x] Create / Update project
- [x] Add repo to project
- [x] Refresh repo list

**Comment by eddiejaoude** [comment]
Similar to #1229

**Comment by webkhushboo** [comment]
Observed below issues:
1. When I go to my projects then it redirects to home page which should not happen.
2. Sign in stuck until refresh
