### ISSUE TITLE
User logging in progress bar should be available on all pages

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1224]
I noticed when logging in from a dashboard page the progress bar is not shown.

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/57545094-ea8daf80-7376-11e9-83a0-143341757a14.png)


I can see the progress bar on dashboard page . Can you please check again
Please see the attached screenshot for your reference.

**Comment by eddiejaoude** [comment]
The screenshot is the home page. If you click on one of the dashboards, then log in?

**Comment by webkhushboo** [comment]
One of the dashboard means, if I click on project ? Is  that you are referring to or something else ?
I agree this will be shown for all components under main module like Home page , help , privacy , profile 
and will not be shown for projects module components. 
I will make those changes now .

Right now I have added the spinner only in main module. Now I will add it to project module too.
Please correct me If I am understanding something wrong.

**Comment by eddiejaoude** [comment]
Yes sorry, by dashboard, I mean the project page (project dashboard) 👍

It needs to be available from all pages because people could login from any page
