### ISSUE TITLE
Lint rule for ending relevant line with a `,`

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1243]
Example usage...

- array
- method signature when vertical
- object

```typescript
constructor(
   a: string,
   b: string,
)
```

**Comment by webkhushboo** [comment]
When I am adding the lint configuration for trailing comma.
Its giving error each property. 
![image](https://user-images.githubusercontent.com/10898595/57948759-2a690f80-7900-11e9-9d0b-5fdb30633469.png)

**Comment by eddiejaoude** [comment]
This is correct, the last object or array item will need a trailing comma too. 

```typescript
{
   field1: '',
   field2: '',
   field3: '',
}
```

```typescript
[
   'item1',
   'item2',
   'item3',
]
```

Looks good 👍
