### ISSUE TITLE
Carton Mascot for DH

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1247]
Using `99design` to get lots of ideas, then can filter down and tweak a short list https://99designs.co.uk/character-mascot-design

**Comment by csengep** [comment]
Had a quick look, I think first we need to provide a design brief so I looked at the criteria for that and will begin to put one together, then post here so you can review.

**Comment by eddiejaoude** [comment]
Ok great, thank you @csengep 👍 . I think we need to also highlight that it needs to be simple enough so that it can also be put on a most swag easily (stickers, hoodies etc)

**Comment by csengep** [comment]
Good point, will make sure to add that!

**Comment by csengep** [comment]
Mascot could do the animated pitch - idea

**Comment by csengep** [comment]
- Start a contest rather than hire one specific designer - from £279
- money back guarantee if no designs are selected 
- I think we should go with something cute and fun, e.g. orange monster with an open source cap/DH logo cap

Questions: 
- which email should I use to sign up? yours, a DH one or mine, I don‘t know how much access to it I would need, how many emails get sent
- something like the GitHub character? something cute like an animal or a monster? or something more professional and relevant like a robot or person?
- target audience: for the brief do we include the managers or just the techies? If we include the managers would that mean the mascot has to be a bit more serious and professional?

**Comment by eddiejaoude** [comment]
Love the ideas 👍 ❤️  (also to get it animated in the near future is a great idea!!)

> which email should I use to sign up? yours, a DH one or mine, I don‘t know how much access to it I would need, how many emails get sent

Good question. I do have an account with them, but we can always create a DH one with a DH email that we can share 🤔 

> something like the GitHub character? something cute like an animal or a monster? or something more professional and relevant like a robot or person?

I think something fun and cute 👍 . If an animal, I would obviously suggest a **rabbit** 😂 , with glasses 🤓 - but I am open to suggestions

> target audience: for the brief do we include the managers or just the techies? If we include the managers would that mean the mascot has to be a bit more serious and professional?

Hmm I think targeted at techies, although it is trying to bridge a gap, but if we target everyone we end up targeting no one, so may be more techies

**Comment by csengep** [comment]
Brief outline draft: 

Describe what your organization or product does and its target audience: We develop a monitoring software for code building and deployment to be used by the tech teams and managers, so everybody is on the same page. Feel free to have a look on dashboardhub.io

Describe what you want designed: We would like a mascot that is simple enough to put on advertising merchandise such as stickers and hoodies. The mascot would primarily be used in marketing for techies so we were thinking something fun and cute. We were thinking either a rabbit with glasses or a cute orange monster with glasses, but are open to other suggestions too. 

Is there anything else you would like to communicate to the designers?: here I would add the link to the logo and colour designs on github

**Comment by eddiejaoude** [comment]
Looks good 👍 .

> Describe what your organization or product does and its target audience

if we could not use the word `monitoring` because it can also mean other things too in the tech world, may be something like this `...dashboard bringing all your software delivery activities in one place...`

> Is there anything else you would like to communicate to the designer

Yep link to assets repo for colours and logo, may be the character could wear a dashboard hub t-shirt (but I don't want to dictate too much and reduce their creativity). To include `open source` would be awesome, I am not sure how though 🤔  - I will ask @andrew-cunliffe , he always has some crazy good ideas 🤓

**Comment by csengep** [comment]
> if we could not use the word `monitoring` because it can also mean other things too in the tech world, may be something like this `...dashboard bringing all your software delivery activities in one place...`

yeah for sure, I will change that

> Yep link to assets repo for colours and logo, may be the character could wear a dashboard hub t-shirt (but I don't want to dictate too much and reduce their creativity). To include `open source` would be awesome, I am not sure how though 🤔 - I will ask @andrew-cunliffe , he always has some crazy good ideas 🤓

I was thinking the opensource logo could be on a baseball cap or something? But the more ideas the better!

**Comment by eddiejaoude** [comment]
I am not sure that most people will recognise the open source logo, so we might have to just write `Open Source` on the t-shirt or cap. What do you think?

**Comment by csengep** [comment]
We could just say in the brief to try include open source somehow and see what they come up with? Or we could just put open source next to the mascot when its on the swag

**Comment by eddiejaoude** [comment]
> We could just say in the brief to try include open source somehow and see what they come up with

❤️ 👍

**Comment by csengep** [comment]
Updated design brief: 

- describe organisation + target audience: 

We develop a software that displays all your activities for code building and deployment in one place, to be used by the tech teams and managers, so everybody is on the same page. Feel free to have a look on dashboardhub.io

- what we want designed:

We would like a mascot that is simple enough to put on advertising merchandise such as stickers and hoodies. The mascot would primarily be used in marketing for techies so we were thinking something fun and cute. We were thinking either a rabbit with glasses or a cute orange monster with glasses, but are open to other suggestions too. 

- other information: 

It would be great if the mascot could somehow include that the company is open source (https://opensource.org/). You can access logos, colours and fonts we use here: https://github.com/DashboardHub/Assets

**Comment by eddiejaoude** [comment]
Looks great 👍

**Comment by eddiejaoude** [comment]
99 design competition started https://99designs.co.uk/character-mascot-design/contests/cute-geeky-fun-rabbit-monster-techies-926295/entries
