### ISSUE TITLE
Dashboard information layout (focus on a single repo in the project dashboard)

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1257]
Information to display that is available from the API (hard code for now)

### High priority
- Latest release 
- Top 5 contributors (with link to their profile page)
- Active branches
- Issues - top 5 active issues
- Milestone - last updated and progress bar
- Pull Requests and their status (CI checks, review required, any issues like conflicts if available in API data)

### Low priority
- Stale branches
- Project board - last updated and progress bar
- Security (do not list, just add an icon with link)

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/58822883-1e968080-8656-11e9-8322-41fc5dbe39a5.png)


Card design is still in progress. Will update once done

Please find the details for above information below
1. Get top contributors:
https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts
2. Get PR List
https://developer.github.com/v3/pulls/
3. Get milestones list:
https://developer.github.com/v3/issues/milestones/

Please let me know if you have any feedbacks on it

**Comment by eddiejaoude** [comment]
I really like the design, its clean and clear 👍 . We might need to make it a bit smaller in the future as we add more information.

Small suggestion:
- I think the icon for `milestone` and `latest pr` might make more sense switched around

Looking forward to seeing more, great work 👍 🤓

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/58957228-d1352300-87bd-11e9-8675-3844da5acbc4.png)

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/58957648-9da6c880-87be-11e9-8fb1-b4522cfde73e.png)

![image](https://user-images.githubusercontent.com/10898595/58957688-ba430080-87be-11e9-8662-1b75441d7441.png)

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/58957739-dd6db000-87be-11e9-98c1-2f008386c944.png)

![image](https://user-images.githubusercontent.com/10898595/58957756-ec546280-87be-11e9-820b-30b91fff4574.png)

**Comment by eddiejaoude** [comment]
Looks good, my initial thought is it looks like the `releases` `events` `milestones` are tabs? Ideally we should try to get all the important information on the first screen and then people can dig deeper if they need (the deeper details can come later)

**Comment by webkhushboo** [comment]
Did you get a chance to look at the app ? How the tabs looks like ? Its appearing on first screen only.

**Comment by eddiejaoude** [comment]
I think we need to not use tabs on this page and try and squeeze the information all on the page (we can hide some information as the screen gets smaller, but initially good to see all the information on the bigger screen size, then we can take away as it gets smaller (later on we can look into responsive not now).

**Comment by webkhushboo** [comment]
@eddiejaoude 
Let's say we will remove the tabs. So what all information should we show on first page ? 
Do you have any suggestion for the design ?

**Comment by eddiejaoude** [comment]
Yes, if we can show as much information on the dashboard without the need for user interaction, as people will probably have it on a big screen where they can not interactive with it to switch tabs. Don't worry too much about the design for now, even simple lists would work, because once we know what information we have, we can revisit the design and even get a designer to help layout the information. If for now we can use things we get out of the box from material design that would be good.

**Comment by webkhushboo** [comment]
c3e853efdcc179ac7438b93b3a8fc233190dfb24

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/59131106-080e6300-898f-11e9-9550-c32e18bfadf3.png)

Added more information in the card. Will update the design after it

**Comment by eddiejaoude** [comment]
@webkhushboo looking great 👍

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/59156494-11e0b500-8aba-11e9-8a1f-95cb80c8c17a.png)

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/59156525-8e739380-8aba-11e9-9bb0-da89940d78df.png)


![image](https://user-images.githubusercontent.com/10898595/59156531-9df2dc80-8aba-11e9-942e-ecfbcf468694.png)

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/59156554-dabed380-8aba-11e9-9973-a36aefe1d207.png)

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/59156626-eeb70500-8abb-11e9-957f-0cf9a811247e.png)

**Comment by eddiejaoude** [comment]
The screenshots look great 👍 .

For the event list, can there be more information to what the event is? Name, type ...

Thanks 🤓

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/59162054-382d4180-8b08-11e9-9b21-35e822325e3d.png)

Please find the attached screenshot 
1. Added event title , event type in the event list. These are populated dynamically 
2. Added PR title and username in Latest PR card and user pic
3. Added contributor profile picture and total commits in top contributor card
4. Added state of milestone , open issues no and closed issues no in milestone card . Also added the profile picture of milestone creator.
5. Added published date in latest release card as well author image.

Please let me know if you have any feedbacks/comments on these

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/59162098-f0f38080-8b08-11e9-8ce0-d8e115021f5c.png)

Adding one more image to show the event title details .. As it is coming in only one event .

**Comment by eddiejaoude** [comment]
Its looking great 👍 . 

I created the issue #1284 to get the new missing data, I think it would be good to do this in the same PR, so that when it is merged into the main branch it will be functional 🤓
