### ISSUE TITLE
Easy setup with Behat plugin

### ISSUE THREAD

**Issue by jeremyquinton** [DashboardHub/PipelineDashboard#127]
### A simple Behat Plugin which does the following
   
* [ ] Before hook => look for a build number.  
* [ ] Generate zip based firefox profile based on configuration (allow parameter for tag/build number)
* [ ] Tests run => data sent somewhere

**Comment by eddiejaoude** [comment]
Going to close this, as I think the Behat plugin should be in its own repo & the generated firefox zip should be in its own repo too.

Firefox: https://github.com/DashboardHub/FirefoxPluginManagement/issues/1
Behat plugin: https://github.com/DashboardHub/BehatPlugin 

Firefox plugin is higher priority as more things depend on it.
