### ISSUE TITLE
Removing repo from project, if last usage delete document

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1285]
- [x] When repo is added/removed to/from a project, store project `uid` in the `repositories` collection (field `projects: string[]`)
- [x] If last project using repo, delete repo document - *probably cleaner in a cloud function when `projects` is empty but as the repo could have lots of updates from Webhooks (future ticket), it could be inefficient, thoughts welcome?*

**Comment by kykyk** [comment]
As for add/remove repos task. There two options that I want to discuss.

1. Trigger-function(onCreate, onDelete....) that would check array of repos changes in particular project. Advantages: more safety and native to Firebase
2. http function for repos updates. Disadvantage: root access to db by default, so I would have to check access.

In addition I have an idea to add one more trigger for repos updates that will check property 'projects' in particular repo in repos collections, if it is emty - trigger will remove repo document. And also I going to wrap this logic into transaction (actually I am doing that now).

**Comment by kykyk** [comment]
Could repo be removed from somewhere except projects collection?
