### ISSUE TITLE
List popular repos on homepage

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1286]
Repos are added to multiple projects, show popular ones on homepage.

Dependent on #1285

- [ ] Read repo `projects.length` and pick top 3
- [ ] Have as 2nd column next to `Active users` and have same max total (3 for both, might to limit the `active users` query)

**Comment by webkhushboo** [comment]
@eddiejaoude 
What all information needs to be shown for popular projects ?

**Comment by webkhushboo** [comment]
@eddiejaoude 
Can you confirm if we have to show public project here or any 3 popular projects?

**Comment by eddiejaoude** [comment]
Public only 👍

**Comment by webkhushboo** [comment]
Thanks for confirming 👍
