### ISSUE TITLE
CRUD monitors for project

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1299]
Within a project we need to add the CRUD **monitors** functionality for `admins` (see screenshot below).

<img width="1035" alt="Screenshot 2019-06-12 11 51 17" src="https://user-images.githubusercontent.com/624760/59332962-75f8b880-8d08-11e9-8d29-aaf3158024ae.png">

## Steps

1. Click new `monitors` button in a project
2. In the new monitors section, there will be `list` page with `delete`, `create` and `edit` page

## Validation

- name is required must be unique within project and have more than 3 characters
- path must be unique with the project

```typescript
// monitor will be under project model
interface Monitor {
   uid: string;
   name: string;
   method:  'GET' | 'POST';
   path: string;
   expectedCode: string;
   expectedText?: string; 
   expectedDuration: number;
}
```

*Notes: Keep the styling vanilla as possible, this will come later*

**Comment by webkhushboo** [comment]
Can you please check these below screenshots for monitors list screen ?
![image](https://user-images.githubusercontent.com/10898595/60035833-6182cb80-96cb-11e9-9fff-4b32a30c0bb1.png)


![image](https://user-images.githubusercontent.com/10898595/60035859-6e072400-96cb-11e9-863b-7d6411efdcba.png)

**Comment by eddiejaoude** [comment]
Looks good 👍. Expected text is optional and expected code probably better if a drop down of popular http status codes (200,201,204,400,401,403,404,500...)

**Comment by webkhushboo** [comment]
Thanks for sharing information 👍 . I will make the changes. Does all the fields except Expected text are required?

**Comment by eddiejaoude** [comment]
yep 👍 - only expected text is optional

**Comment by webkhushboo** [comment]
Thanks for the confirmation 👍
