### ISSUE TITLE
display data for latest release

### ISSUE THREAD

**Issue by webkhushboo** [DashboardHub/PipelineDashboard#1316]
### Requirements

**UI**
- [ ] Display data for latest release info 
1. Release version
2. Released date

**Comment by webkhushboo** [comment]
Latest release card screenshot : 
![image](https://user-images.githubusercontent.com/10898595/59708628-c600df00-9222-11e9-9149-333b3d3a96d4.png)



Latest release card screenshot when no data available
![image](https://user-images.githubusercontent.com/10898595/59709194-d06fa880-9223-11e9-9dda-66276c470a8a.png)

**Comment by eddiejaoude** [comment]
I get an error sometimes, may be when there is no data to sort?

<img width="1679" alt="Screenshot 2019-06-18 22 20 54" src="https://user-images.githubusercontent.com/624760/59709281-71a43200-9217-11e9-9e9c-8d83c36ae980.png">

**Comment by webkhushboo** [comment]
Good catch. I will fix this error

**Comment by webkhushboo** [comment]
Fixed the above sorting error. Please pull the latest changes and validate
