### ISSUE TITLE
Add url to project

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1339]
Need to add `url` to project (`project.url`) with validation. Strip off trailing `/`

**Comment by webkhushboo** [comment]
Url will be optional or mandatory ?

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/60365813-63b89300-9a07-11e9-8d02-a5904facf930.png)

Please see the attached screenshot for url .

**Comment by webkhushboo** [comment]
Do we need to show this URL on home page or my projects ?

**Comment by eddiejaoude** [comment]
Good question. It will be optional and if it can be displayed on the project dashboard page
