### ISSUE TITLE
Breadcrumb to pages under project (tokens, monitors)

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1342]
Need a way for the user to get back to the project dashboard without using the back button.

Clickable breadcrumb would be easier for people to read and to click to get back to the project dashboard

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/60617449-68a78900-9df1-11e9-9f89-e656871bc82c.png)


We can add one link for going back to project list page. Please check the attached screenshot

**Comment by webkhushboo** [comment]
For tokens pages
![image](https://user-images.githubusercontent.com/10898595/60617663-ce941080-9df1-11e9-8577-a91168d1b331.png)

**Comment by eddiejaoude** [comment]
I was thinking may be above the title have text like `project name / monitors` with the project name as a link and monitors as text? the same for tokens

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/60668799-6e9d7880-9e8a-11e9-9369-5fb71bc21780.png)

**Comment by eddiejaoude** [comment]
Yes looks great 👍
