### ISSUE TITLE
Under monitor display list of pings

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1355]
When click on monitor to get details, show a list of pings in date order.

**Comment by webkhushboo** [comment]
Do you want me to display the list of pings in similar manner as we have for monitors screen? 
It will be new page with route projects/{projectId}/monitors/{monitorId}/pings
Please confirm

**Comment by eddiejaoude** [comment]
Yes please, that route looks good 👍

**Comment by webkhushboo** [comment]
Thanks
