### ISSUE TITLE
Monitor manual ping debounce / limit (1min)

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1359]
- store latest manual ping date in monitor
- disable manual ping button using the stored date for 1 min (therefore any other browsers / computers logged in can not abuse)

![image](https://user-images.githubusercontent.com/10898595/61580581-78cda100-ab31-11e9-932b-b114034281bd.png)

**Comment by webkhushboo** [comment]
@eddiejaoude 
Just a question:

When I do ping I am storing ping info to ping collection via function call . So I have to store the latest ping date in monitor array .So here  , should I use function to update the monitor details or should i update using query here only?
If I am storing here using query only then I have to do get call for that monitor using monitor id to get it details and update it .
There will be many calls to just block the next ping .. Instead we should show loader on ping button for 1 minute when click on ping button
What do you think ?

**Comment by eddiejaoude** [comment]
> store the latest ping date in monitor

I think it is probably best to do it in the `ping` function, it will already have the monitor information, it will just need to do an extra save once the ping is completed - it won't block any other pings because they would be a new function. May be with a structure like this...

```typescript
MonitorModel {
   latestPing: PingModel;
   // ...
}
```

> show loader on ping button for 1 minute when click on ping button

This is probable the simplest option, but they could open a new browser and keep sending more manual pings or refresh the page. But I think this would be best for now. Could you do it so that the text in the button is changed to a loader and the button is disabled

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/61579429-98110200-ab22-11e9-9d2e-d4460c498f5c.png)

Can you please check how does it look like ?
