### ISSUE TITLE
Monitor to store ping aggregations

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1360]
- ~~store latest ping~~ Done in #1359 
- total successful pings counter
- total unsuccessful pings counter
- monitor list to show latest ping and total pings
- update monitor list to update in realtime similar to pings list

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/61593042-1be8ee00-abf8-11e9-890b-8a3aaaa54d6f.png)


Can you please check this monitor page ? Please let me know your suggestions.
