### ISSUE TITLE
Monitor deleted, delete related pings

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1361]
When deleting a monitor, need to delete all the related pings

**Comment by webkhushboo** [comment]
@eddiejaoude 
We have to save monitorUid under pings collection.

**Comment by eddiejaoude** [comment]
Yes, we need this also when listing the pings for a monitor (in a future ticket)

**Comment by eddiejaoude** [comment]
I have an idea, instead of calling the sub collection `pings`, we call it by the `monitorUid`, that way when we want to get a list of pings for a monitor or delete all the pings for a monitor, it is much easier
