### ISSUE TITLE
When delete project delete all pings

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1367]
Delete all sub collections. Currently only `pings`, don't get monitor uids, just delete all `pings` under the `project`

**Comment by webkhushboo** [comment]
@eddiejaoude 
When I will delete one project , I have to take the monitor uid's to delete all pings because pings are created based upon the monitor uid only.
If I delete all pings when one project deleted , then it will be wrong implementation.
What do you think on this?

**Comment by eddiejaoude** [comment]
Discussed in Slack, but here are my notes:

Two options
1. Deleting all pings in a project is fine because they all need to go, but this could be large
2. On project delete trigger, get all monitors and call existing function to delete pings by monitor uid and project uid

I prefer option 2

**Comment by webkhushboo** [comment]
@eddiejaoude 
I have implemented the option 2. Please have a look and let me know your feedbacks
