### ISSUE TITLE
Show monitors and latest ping status on the dashboard page

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1368]
Dependant on #1360

**Comment by eddiejaoude** [comment]
Duplicate

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/62410601-56de1f00-b605-11e9-920b-6b0055fd6401.png)

Can you please check if this looks okay ? Please provide your feedback
