### ISSUE TITLE
Badges on monitors, tokens, repositories buttons on the project page

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1383]
Show total badges on monitors, tokens, repositories buttons on the project page

<img width="1389" alt="Screenshot 2019-08-03 15 09 55" src="https://user-images.githubusercontent.com/624760/62412933-d7e6e780-b600-11e9-86f3-0fa788787616.png">

**Comment by webkhushboo** [comment]
Please check the attached screenshot

![image](https://user-images.githubusercontent.com/10898595/62421251-8d2aa580-b6bc-11e9-80da-01c3080c5a0f.png)
