### ISSUE TITLE
Homepage show more information about the project

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1385]
On the home page, we list the projects with basic information, also show:

- total repositories
- total monitors with total pings

For example...

<img width="1394" alt="Screenshot 2019-08-03 15 08 32" src="https://user-images.githubusercontent.com/624760/62412920-a706b280-b600-11e9-9407-a939f19d2cd6.png">

**Comment by webkhushboo** [comment]
Please find the attached screenshot for your reference. Kindly provide your feedback
https://dashboardhub.slack.com/files/UJVUA12F2/FLQ495Y10/image.png
