### ISSUE TITLE
Limit monitor add to 3 per project

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1388]
Disabled the monitor `add` button if already 3 monitors and add tool tip to button saying limit of 3 reach

- Also need a route guard, so no one can navigate using the url

**Comment by webkhushboo** [comment]
![image](https://user-images.githubusercontent.com/10898595/62488704-99108780-b7e2-11e9-96ad-75511db5c295.png)

Please check the attached screenshot for your reference

**Comment by eddiejaoude** [comment]
Looks good, but I don't think it will be consistent or possible to be consistent with the rest of the site. There is space here, but in other places I do not think there will be space for such a message.

May be a be alert box similar to here , what do you think? https://github.com/DashboardHub/PipelineDashboard/blob/v0.11.6/web/src/app/monitors/monitors-list/monitors-list.component.html#L5

**Comment by webkhushboo** [comment]
@eddiejaoude 
As discussed , updated the tooltip position to top.  Please find the attached screenshot for your reference.
![image](https://user-images.githubusercontent.com/10898595/62490168-4afd8300-b7e6-11e9-8ea5-58f4365adb5e.png)
