### ISSUE TITLE
Key of repository collection should be changed to generated UID

### ISSUE THREAD

**Issue by kykyk** [DashboardHub/PipelineDashboard#1411]
If user wants to rename repo, we should change key of repos collection in database as it consists of username and repo name, but it is impossible.

- [x] generate key UID automatically
- [x] change logic of CRUD operations and queries in 'web' and 'function'

**Comment by eddiejaoude** [comment]
One solution to this, is they remove it from the project and re-add it again, but you are right it is not ideal because everyone will need to do this and then Webhooks would have to be re-created again.

Does the repo rename come in via a webhook event?

**Comment by kykyk** [comment]
> One solution to this, is they remove it from the project and re-add it again, but you are right it is not ideal because everyone will need to do this and then Webhooks would have to be re-created again.
> 
> Does the repo rename come in via a webhook event?

Webhook has a RepositoryEvent, this event includes a 'rename' action
https://developer.github.com/v3/activity/events/types/#repositoryevent

**Comment by eddiejaoude** [comment]
> this event includes a 'rename' action

Ok great 👍
