### ISSUE TITLE
Design: Implement design of project

### ISSUE THREAD

**Issue by AntonBeLkaA** [DashboardHub/PipelineDashboard#1420]
### Implement design of [project page](https://xd.adobe.com/spec/7fa5b10b-c020-438e-6e62-4b735648fac8-0994)

**UI**
- Change global styles (colors, etc..)
- Change style of next components: repository, monitor-summary, view, homepage, privacy, profile, project-list, terms-conditions, create-edit, help

![Screenshot from 2019-08-23 10-35-56](https://user-images.githubusercontent.com/54395702/63575102-f00fae00-c591-11e9-927f-02c0ef417b68.png)

![Screenshot from 2019-08-28 18-33-18](https://user-images.githubusercontent.com/54395702/63870421-9d375b80-c9c2-11e9-8fa3-adccccfe1969.png)
![Screenshot from 2019-08-28 18-33-28](https://user-images.githubusercontent.com/54395702/63870424-9f011f00-c9c2-11e9-862a-401893c43fe5.png)
![Screenshot from 2019-08-28 18-33-39](https://user-images.githubusercontent.com/54395702/63870431-a1637900-c9c2-11e9-8262-bbe8b0380428.png)
![Screenshot from 2019-08-28 18-33-49](https://user-images.githubusercontent.com/54395702/63870434-a294a600-c9c2-11e9-9a6d-b3a0a1861705.png)
![Screenshot from 2019-08-28 18-34-01](https://user-images.githubusercontent.com/54395702/63870442-a45e6980-c9c2-11e9-8c81-3edb65dbe21b.png)
![Screenshot from 2019-08-28 18-34-11](https://user-images.githubusercontent.com/54395702/63870446-a6282d00-c9c2-11e9-8f08-f04df93fa2af.png)
![Screenshot from 2019-08-28 18-34-20](https://user-images.githubusercontent.com/54395702/63870449-a7595a00-c9c2-11e9-9cef-1e9ab19a6510.png)

**Comment by eddiejaoude** [comment]
Great, thank you @AntonBeLkaA 👍 . Can you add a screenshot to the description please 🤓
