### ISSUE TITLE
Error page (404)

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1422]
Create error module and catch all UI routing that is not matched and create a `404` page using the mascot with ears down...

![5](https://user-images.githubusercontent.com/624760/63747487-31a89d80-c89f-11e9-87c1-1d806ec8a452.png)

**Comment by webkhushboo** [comment]
Please see the attached screenshot for your reference 
![image](https://user-images.githubusercontent.com/10898595/63882771-506a7980-c9f0-11e9-8b46-3d9c8ca3a8c8.png)
