### ISSUE TITLE
Imports to use `@shared` and `@core` to simplify paths

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1423]
Imports to use `@shared` and `@core` to simplify [imports](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping)

This will make import paths cleaner 

tsconfig should be below
```
"paths": {
      "@shared/*": ["src/app/shared/*"],
      "@core/*": ["src/app/core/*"]
    }
```

**Comment by webkhushboo** [comment]
@eddiejaoude 
We can define paths for shared and core modules to use @shared and @core . Can you please confirm the path for using @dh

**Comment by eddiejaoude** [comment]
Sounds good 👍

**Comment by webkhushboo** [comment]
Thanks for confirming . I have used the config for `@shared` and `@core`
