### ISSUE TITLE
60mins monitor sometimes throws an error (I guess when url is invalid?)

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1427]
Not part of this but I see an error occasionally in the logs for running the pings every 60 mins

*Note: it might be for invalid urls*

```
Error: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field monitors.`1`.latestPing.expectedText).
```

<img width="1281" alt="Screenshot 2019-08-24 08 38 28" src="https://user-images.githubusercontent.com/624760/63634169-a33bde00-c64a-11e9-9ac0-43c1813e4b78.png">

**Comment by webkhushboo** [comment]
@eddiejaoude 

When the URL is invalid , it throws an error 
```
{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{},"authenticationInfo":{"principalEmail":"web.khushboo@gmail.com"},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"projects/pipelinedashboard-khush/locations/us-central1/functions/responseGitWebhookRepository"}
```

What should be the status code when there is error ? Should we write something like `500` and message `Internal Server Error`

**Comment by eddiejaoude** [comment]
If there is an invalid url, I think we catch it and record a `404`
