### ISSUE TITLE
Webhook per application installation not for DH

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1428]
Some people might use multiple installations, so a repo may have multiple Webhooks.

Maybe we can append the webhook name from the `environments.ts` with `firebase.projectId`?

**Comment by JsssCode** [comment]
We cannot set a name for webhook, but webhook can be detected by URL

**Comment by kykyk** [comment]
We cannot set a name for webhook, but webhook can be detected by URL

**Comment by eddiejaoude** [comment]
> webhook can be detected by URL

Makes sense and solves the problem of allowing multiple Webhooks for different deployments 👍 . Can you please update this and create a new PR.

Can you also update the webhook events to send **all** webhooks events to us (if the type is not match then it is ignored) - the reason for this is as we add more functionality to the functions to save more data from the events, the webhook does not need to be updated

**Comment by kykyk** [comment]
> Makes sense and solves the problem of allowing multiple Webhooks for different deployments  . Can you please update this and create a new PR.
Webhook search on URL was implemented together with PR #1124 

> Can you also update the webhook events to send **all** webhooks events to us (if the type is not match then it is ignored) - the reason for this is as we add more functionality to the functions to save more data from the events, the webhook does not need to be updated
Ok, I will done in PR #1123

**Comment by eddiejaoude** [comment]
> Webhook search on URL was implemented together with PR #1124

Oh great 👍 . I checked the code, you are right it is already done with the URL 👍 🤓 

> Ok, I will done in PR #1123

Thank you 👍
