### ISSUE TITLE
Scrutinizer data not coming through - API changed?

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#144]
Fixed for `develop` & merge in all release branches

**Comment by eddiejaoude** [comment]
API has not changed. Bad coding on my part. Will fix now.

**Comment by brettminnie** [comment]
Should have blamed the API :D

**Comment by eddiejaoude** [comment]
LOL :D ... I couldn't do that to the poor scrutinizer ;)

**Comment by brettminnie** [comment]
But it didn't actually stand up to scrutiny now did it :P

**Comment by eddiejaoude** [comment]
![screenshot 2015-04-15 15 40 18](https://cloud.githubusercontent.com/assets/624760/7161196/bede11ac-e385-11e4-859f-ce8d4d5e4df4.png)
