### ISSUE TITLE
Increment pings not with +1 but firebase way

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1526]
In `functions/src/monitor/monitor.ts`

It has 

```typescript
if (pingResult.isValid) {
    monitor.successfulPings = monitor.successfulPings ? monitor.successfulPings + 1 : 1;
  } else {
    monitor.unsuccessfulPings = monitor.unsuccessfulPings ? monitor.unsuccessfulPings + 1 : 1;
  }
```

But it should be done the **firestore** recommended way. Please also search code base for `+ 1` to check we don't do it anywhere else.

**Comment by webkhushboo** [comment]
@eddiejaoude 

Monitor is an array inside document , and firebase way to increment the value by 1 applicable on document fields
I tried to change the value using Increment function but its not working with field inside array inside document.
It only works with field inside document.

**Comment by webkhushboo** [comment]
@eddiejaoude 
I have verified , we are not using +1 at any other places in the application

**Comment by eddiejaoude** [comment]
Thank you for clarifying both 👍
