### ISSUE TITLE
Follow project(s)

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1541]
The ability to star/favourite/follow a public project

- On the project dashboard, have a follow button after the project name and display how many people are following the project (counter see below)
- Store project `uid` under the user doc collection store
   - `user.following: string[]`
- Page to list the projects the user follows -- This will be implemented in task #1547 
- Increment project counter `project.followers: number` (display on project page, see above)

Issue
- If project gets deleted? Show project as missing?

**Comment by webkhushboo** [comment]
I think I found a bug while follow and unfollow . I was able to click multiple times on follow and unfollow and count is increasing multiple times too.

![image](https://user-images.githubusercontent.com/10898595/67228421-da661a00-f456-11e9-8623-a1ddbcc467ac.png)

**Comment by eddiejaoude** [comment]
Ah good spot. Can you please raise an issue and assign it to yourself? I think we need a `debounce` on the button for may be 1s

**Comment by eddiejaoude** [comment]
Raised issue https://github.com/DashboardHub/PipelineDashboard/issues/1574
