### ISSUE TITLE
Build time

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1555]
We show build status, are we able to get the time it took to build on CI?

Note: check for webhook from GitHub

**Comment by webkhushboo** [comment]
@eddiejaoude 

I can see there are two build times

```
continuous-integration/travis-ci/pr — The Travis CI build passed
continuous-integration/travis-ci/push — The Travis CI build passed 
```

which one do you want to show ?

**Comment by eddiejaoude** [comment]
I suggest we save both data and display the `PR`. In the future we can either change the one we display or display both
