### ISSUE TITLE
Rename "most active users" to "most recent users" on the homepage

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1559]
<img width="2138" alt="Screenshot 2019-10-09 15 51 42" src="https://user-images.githubusercontent.com/624760/66492721-c280b480-eaac-11e9-8317-78aa3d659adf.png">

**Comment by richardhooper** [comment]
I'm happy to take a look at this. 😄

**Comment by richardhooper** [comment]
❓ Currently that pane has a main title of "Active Users" and a subtitle of "Most active users".  Is this issue only to change the subtitle to "Most recent users", or the main title as well?

**Comment by eddiejaoude** [comment]
I think just the subtitle for now 👍
