### ISSUE TITLE
Save & show more PR information

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1560]
Map, save and display the following extra information:

```
  "comments": 10,
  "review_comments": 0,
  "maintainer_can_modify": true,
  "commits": 3,
  "additions": 100,
  "deletions": 3,
  "changed_files": 5
```

Notes:
- Get initial information when getting the repo information in `info.ts`
- Any new information via a `webhook`

**Comment by webkhushboo** [comment]
@eddiejaoude 

This information is available in Single PR information . So we need to create cloud function for retrieving the PR info by issue number. Then we need to call this cloud function for each PR by issue number and map the data on Front end.

These are my thoughts on this above. Please correct me if I am wrong.

**Comment by eddiejaoude** [comment]
Yes you are right, this information is only available on the get pull request by id `GET /repos/:owner/:repo/pulls/:pull_number` https://developer.github.com/v3/pulls/#get-a-single-pull-request

Leave this one on the backlog/todo column for the moment and let me have a think

**Comment by eddiejaoude** [comment]
In `functions/src/repository/info.ts` when getting the list of Pull Requests, we can do a promise all to get the extra information for each pull request and add it to the existing pull request model.

Note: this will make this function take a bit longer, but we can look at optimising later on
