### ISSUE TITLE
Pull request list in project dashboard to show last updated as well as when created

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1580]
Currently showing when PR was created, it will be useful to show when last updated, to match the PR events 

<img width="822" alt="Screenshot 2019-10-26 17 36 58" src="https://user-images.githubusercontent.com/624760/67622926-3a720d00-f817-11e9-8e42-08f482755751.png">

**Comment by webkhushboo** [comment]
@eddiejaoude 

I have added  the updatedOn time for Pull Request. Kindly check below screenshots.

Desktop:
![image](https://user-images.githubusercontent.com/10898595/67633829-e92b5180-f8da-11e9-84cf-a5938312fafe.png)

Mobile:
![image](https://user-images.githubusercontent.com/10898595/67633813-b6815900-f8da-11e9-888f-052506545ff7.png)
