### ISSUE TITLE
Map webhook CommitCommentEvent

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1587]
Discovered in #1586

**Comment by webkhushboo** [comment]
@eddiejaoude 

I have checked `CommitCommentEvent`. It was only triggered when there is any comment on any commit. It was returning just the comment object and not able to figure out for which PR it is. 
We need to show the comments count for each PR. So when I was adding any comment on PR `issueCommentEvent` was getting fired and its also sending issue number in the response. 

So I have added the support for saving the real time comments count for each PR in this already exist function. 

So I think we don't need to map `CommitCommentEvent` too.
Kindly review and let me know in case of any questions.

**Comment by eddiejaoude** [comment]
if we don't need it, then great, less code to write 👍
