### ISSUE TITLE
Map webhook PullRequestReviewEvent

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1588]
Discovered in #1586

**Comment by webkhushboo** [comment]
@eddiejaoude 

This event Triggered when a pull request review is submitted into a non-pending state, the body is edited, or the review is dismissed and right now we are not showing any of these information's
We are just showing `comments, review_comments,commits,changed files`
We were able to show real time data for all `review_comments,commits,changed files` Only comments is left. This will be covered in #1587

So closing it as we are not interested in if it is dismissed or edited
