### ISSUE TITLE
When new data not available, app breaks

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1597]
On `dev` where it has old data (which will happen on production), the app breaks, one example is...

<img width="1913" alt="Screenshot 2019-11-04 18 33 28" src="https://user-images.githubusercontent.com/624760/68147304-af3cf980-ff31-11e9-8f86-a9c2aa6eeb89.png">

**Comment by webkhushboo** [comment]
@eddiejaoude 

Can you tell me the steps to reproduce this issue ?

**Comment by eddiejaoude** [comment]
When visiting this url and project dashboard on `dev` (note: I am logged in as the owner of the project) https://pipeline-dev.dashboardhub.io/projects/02b2e6eb-f8ce-4559-90d9-23ad9d6d3962

It is probably because the data in the DB does not have the new fields, which is expected, so we need to accommodate if the data does not exist
