### ISSUE TITLE
Automated testing part 2 -statistics

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1601]
Note: no mocking, this will be end-to-end testing

1. update db
2. check numbers on homepage

**Comment by webkhushboo** [comment]
@eddiejaoude 

To update db , we need to add project/ping/events . Before that we need to login.
We need test account for login .

**Comment by eddiejaoude** [comment]
We can update via the step defs directly to the DB, and then test this information on the homepage as `guest`s can see it too
