### ISSUE TITLE
Automated test part 3 - public projects

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1606]
- Insert a public project into the DB (currently we only do fields, we need a way to insert a whole json file) - also put the date in the future so it appears at the top of the list
- Insert a private project and check it does not appear in the list

**Comment by webkhushboo** [comment]
@eddiejaoude 

"also put the date in the future so it appears at the top of the list" . Which date you are referring here ?

**Comment by eddiejaoude** [comment]
I think the projects are listed by last updated date descending? So best to save the one we are testing to something like `2050-01-01` so it is always at the top
