### ISSUE TITLE
Test project dashboard page as guest

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1611]
Project with minimum information:
- title
- no repositories are listed
- owner notifications do not show (these tests will fail at the moment, I think we have open PRs for these?) 
   - `You do not have any monitors. Please create monitor`
   - `You do not have any repositories. Please connect repository`
- with no data saved check for
   - latest release `No releases are available`
   - milestone `No milestones are available`
   - top contributor 
   - latest PR `No PR are available`
   - Issues
   - pull requests
   - events

Project with full information (and with 2 repositories)
- amount of repositories card match the amount of repositories
- save the following fields and test they are displayed correctly
   - latest release
   - milestone
   - top contributor 
   - latest PR
   - Issues
   - pull requests
   - events

**Comment by webkhushboo** [comment]
@eddiejaoude 

I have a questions on this
I Can not store project as guest. I can just verify what is already there

**Comment by eddiejaoude** [comment]
In the `Given` step def we are admin, so we can store it as `User A` - later we can auto generate users to make it more realistic
