### ISSUE TITLE
When testing items in a list, we need to find the row and check that row

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1617]
For example:
- user
- repositories
- monitors
- pings
- last updated date

**Comment by webkhushboo** [comment]
@eddiejaoude 
If there are `n` projects already added to the projects collection then how we would know which no of row is added in the collection ?

I think when we delete all the documents in the collection and we do test then it should appear at the first row based upon the time.

What do you think ?

**Comment by eddiejaoude** [comment]
We should give this one a date in the future so it will appear at the top of the list. I don't this deleting is a good idea because we already are having issues with that and race conditions.

**Comment by webkhushboo** [comment]
If there are few records already present in the collection then they come like this 

![image](https://user-images.githubusercontent.com/10898595/70447425-adcc9700-1ac4-11ea-9021-ab507b6134df.png)

**Comment by eddiejaoude** [comment]
I think it is best to search for the name/title, then capture that row and check the columns in that row number

**Comment by webkhushboo** [comment]
@eddiejaoude 
I searched for title then find the row . It returns the row element so we can verify in that element.

**Comment by eddiejaoude** [comment]
ok great 👍
