### ISSUE TITLE
Delete pings after 1 month old

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1627]
Do we do this already? Or something similar. We do not need to store such a big history for pings

**Comment by webkhushboo** [comment]
@eddiejaoude 
Its been already implemented. I have verified functions.
There is a function `deletePingsAfter30days` which is checking for all project pings and deleting them if older than 30days.

Let me know if anything else needs to be done here.

**Comment by eddiejaoude** [comment]
Ok great, thank you 👍
