### ISSUE TITLE
Project sub navigation needs to become responsive sooner

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1641]
When resizing on the project page, the sub navigation is unreadable before it changes to a responsive drop down.

I think it should change to a responsive dropdown sooner

<img width="682" alt="Screenshot 2019-12-27 07 48 57" src="https://user-images.githubusercontent.com/624760/71507766-87a54600-287d-11ea-880c-67263b3cb5c4.png">

**Comment by webkhushboo** [comment]
@eddiejaoude 

I can see on dev, its already changes to responsive. Can you please share when do you see the above issues ? If possible share the width where you find it .

![image](https://user-images.githubusercontent.com/10898595/71781093-c612d180-2ff0-11ea-8d32-ff30c70a580b.png)
.

**Comment by eddiejaoude** [comment]
I can not replicate this anymore, I will close for now
