### ISSUE TITLE
Spike: Twitter Wall

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1665]
Similar to https://app.taggbox.com/TwitterWall/index?field=%23google&type=1

1. Is Twitters realtime API public or do we have server keys for it
   i. if public can the UI talk directly to it
2. can we use firebase with Twitters realtime API

**Comment by webkhushboo** [comment]
Yes twitter realtime API's are available. 
Getting started with developer
https://developer.twitter.com/en/docs/basics/getting-started

The included endpoints will let you perform the following:

1. Post, retrieve, and engage with Tweets and timelines
2. Post and receive direct messages
3. Manage and pull public account information
4. Create and manage lists
5. Follow, search and get users
6. Retrieve trends

API's for tweets and users
https://developer.twitter.com/en/docs/labs/tweets-and-users/api-reference

**Comment by webkhushboo** [comment]
Please find the below findings on twitter API.

**API response for realtime data:**

```
{
  "data": [
    {
      "id": "1067094924124872705",
      "created_at": "2018-11-26T16:37:10.000Z",
      "text": "Just getting started with Twitter APIs? Find out what you need in order to build an app. Watch this video! https://t.co/Hg8nkfoizN",
      "author_id": "2244994945",
      "attachments": {
        "media_keys": [
          "13_1064638969197977600"
        ]
      },
      "entities": {
        "urls": [
          {
            "start": 107,
            "end": 130,
            "url": "https://t.co/Hg8nkfoizN"
          }
        ]
      },
      "format": "default"
    }
  ]
}
```

**Webhooks for providing real time data** 
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/guides/getting-started-with-webhooks

**Filters on real time API**
![image](https://user-images.githubusercontent.com/10898595/73604992-a86c6400-45be-11ea-8081-90244e368733.png)

**Parameter track:** The text of the Tweet and some entity fields are considered for matches. Specifically, the text attribute of the Tweet, expanded_url and display_url for links and media, text for hashtags, and screen_name for user mentions are checked for matches.

**Pricing for API's providing real time data**
![image](https://user-images.githubusercontent.com/10898595/73604976-4dd30800-45be-11ea-925c-1af3dad56153.png)
