### ISSUE TITLE
Breadcrumb on Pings page does not work

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#1666]
https://pipeline.dashboardhub.io/projects/a2f2573e-fe98-48ad-9246-f701a6a187f6/monitors/d7f91ca1-93e3-484c-a045-430a66842fbe/pings

**Comment by webkhushboo** [comment]
Its working for me . Can you please share the steps and this mentioned URL https://pipeline.dashboardhub.io/projects/a2f2573e-fe98-48ad-9246-f701a6a187f6/monitors/d7f91ca1-93e3-484c-a045-430a66842fbe/pings is taking directly to homepage.

**Comment by eddiejaoude** [comment]
Yes you are right, it does work 👍  - I think I was not patient enough 🤦 

Thank you for retesting, I will close the issue
