### ISSUE TITLE
Badge to your dashboard & link on the Dashboard page

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#18]
* Markdown badge
* When viewing Dashboard for Project, display markdown link
* Cache

eg. 
Link: https://img.shields.io/badge/DashboardHub-Ready-green.svg

Markdown: ![DashboardHub Badge](https://img.shields.io/badge/DashboardHub-Ready-green.svg "DashboardHub Badge")

**Comment by phpeuro** [comment]
Yes please! :+1: :bulb:

**Comment by eddiejaoude** [comment]
I need to sort out domain first, otherwise people would have to get a new badge later on with new url. 

`DashboardHub.com` is already taken :cry:

**Comment by Netsensia** [comment]
dashboardclub :)

**Comment by software-programmer** [comment]
Surely it's dashboardhub.io nowadays

**Comment by eddiejaoude** [comment]
@software-programmer :+1: Good point. Done! Now just to config it :smile:

**Comment by eddiejaoude** [comment]
I am going to bump this feature from the **Prototype** to the proper App to avoid confusion.

**Comment by eddiejaoude** [comment]
Getting onto this one soon :smile:

**Comment by eddiejaoude** [comment]
Badge added to Dashboard. When clicked shows Markdown & html code to use.

![screenshot 2015-03-29 13 00 39](https://cloud.githubusercontent.com/assets/624760/6885336/baea658e-d613-11e4-9641-f2fa9a04623c.png)

![screenshot 2015-03-29 13 00 46](https://cloud.githubusercontent.com/assets/624760/6885337/baec71ee-d613-11e4-9313-dbc226c197ee.png)

Creating PR now.
