### ISSUE TITLE
Implement cache for MVP

### ISSUE THREAD

**Issue by simoncasey** [DashboardHub/PipelineDashboard#184]
- [x] Configure Spring caching abstraction
- [x] Use simple cache implementation eg Google Guava
- [ ] Create beans for interacting with cache throughout the app

**Comment by simoncasey** [comment]
Enabling the cache in spring only envolved adding a dependency and annotation. Once we have something to cache, we can explore more

**Comment by eddiejaoude** [comment]
:+1: Sounds good. Keep it simple for now :smile:
