### ISSUE TITLE
Add to TravisCI

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#188]
* [x] TravisCI

**Comment by simoncasey** [comment]
@eddiejaoude I had a look around and there isn't any cloud-based one that I can see. This kinda stuff is mostly done as mvn/gradle/ant plugins in Java-land. Supposedly Scrutinizer are working on it but who knows when that will be.

**Comment by eddiejaoude** [comment]
Ok, fair enough. Do you have any links to any decent plugins for this?
