### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#196]
* [ ] Add to build process (inc. TravisCI)
* [ ] Remove from Scrutinizer as does not support Java - @simoncasey is there a Java alternative to Scrutinizer?

**Comment by simoncasey** [comment]
popular choice is to integrate PMD:
https://pmd.github.io/pmd-5.4.1/
but it can be quite spammy

**Comment by simoncasey** [comment]
I suggest we go for coverity with the travis integration:
https://scan.coverity.com/travis_ci
