### ISSUE TITLE
Running Dashboard on GitPages

### ISSUE THREAD

**Issue by dxwood** [DashboardHub/PipelineDashboard#34]
Remove the dependancy on having external service to display the dashboard and also the ability to put the core code and config into your Git Repo and have a dashboard and a code base in the same place.

**Comment by eddiejaoude** [comment]
This is probably one for the AngularJs version of the project https://github.com/DashboardHub/PipelineDashboardAngular

**Comment by eddiejaoude** [comment]
Github Pages https://pages.github.com

**Comment by andrew-cunliffe** [comment]
With the assumption this relates to having a stand alone web page (with no server requirement, its just a static web site) then yes something like Angular and a SPA would work, however there are still considerations that might lean towards wanting a server.

For example, you want to store a private API key, would you want to provide this to other users to input in their browser as there is no DB / server to provide this? Normally I would say API keys should be stored in a two-way encryption within a database and only transferred over HTTPS.

Also there is a matter of cache or creating historic statistics, some of these might have APIs available but other times you might want your sever to hold some data.

Part of this depend on how you want your project to evolve.... now there is an interesting option with the Angular version, we could put a simple NodeJS server behind it for these things, then for those wanting to just run the HTML locally without security issues they can, but for those that require a higher level of protection they could run up the lightweight NodeJS version that can in turn host up the Angular site (JavaScript gets pretty cool with things like that)
