### ISSUE TITLE
Basic informational Homepage

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#44]

**Comment by eddiejaoude** [comment]
![screenshot 2015-03-02 12 55 27](https://cloud.githubusercontent.com/assets/624760/6441037/757ce4ba-c0db-11e4-8454-92998b40d97b.png)

**Comment by brettminnie** [comment]
Etc al should read et al or etc.

**Comment by eddiejaoude** [comment]
> Etc al should read et al or etc.

Is that English?

**Comment by brettminnie** [comment]
etc is short for etcetera, it's accepted, et al is french I think but
commonly used in the english language
