### ISSUE TITLE
Enforce token name to be unique with account

### ISSUE THREAD

**Issue by theodosiakefala** [DashboardHub/PipelineDashboard#453]
Unique token to that environment 

- [ ] UI validation for better ux
- [ ] API enforce validation

**Comment by kartikpandey2** [comment]
@eddiejaoude  Can you please describe this issue 😅

**Comment by kartikpandey2** [comment]
@eddiejaoude  will prefer logic but the design will also work.

**Comment by eddiejaoude** [comment]
@kartikpandey2 ok cool 👍 . I need to get the foundations in first, then multiple people can work on it 🤓 . Ping me in a week and hopefully I will be there

**Comment by eddiejaoude** [comment]
Implemented in the new version
