### ISSUE TITLE
Manual deploy in new design

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#591]
Dependent on #800 

An alternative to using the curl command, the form can be used for manual releases.

Form on the release list page (similar to the token list page) with these fields:

- version (string)
- token (dropdown of their tokens for that environment)
- state (startBuild...finishDeploy - depending on their environment type)

**Comment by chowbertilla** [comment]
@eddiejaoude  pushed but still need to get it looking nicer and the UX to be smoother
