### ISSUE TITLE
Monitoring CRUD in new design

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#600]
### Requirements

**API**
- [ ] Task One
- [ ] Task Two

**UI**
- [ ] Task One
- [ ] Task Two

**Comment by sarajaoude** [comment]
<img width="2413" alt="screenshot 2018-02-16 18 34 30" src="https://user-images.githubusercontent.com/11989248/36323219-12f0a15c-1348-11e8-98bc-60f9b978ba2e.png">
