### ISSUE TITLE
Behat tests to bypass the OAuth login 

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#62]

**Comment by eddiejaoude** [comment]
Tried a few approaches, none worked.

**Comment by jaffamonkey** [comment]
Assuming UI tests: Use session tokens that do not expire, then you can pass them in request header for tests you want to bypass login process.  Other option is to enable method to turning authentication off, for specific tests.  But there is good argument that authentication should be part of every test, as a passing test without it, runs risk masking an issue.
