### ISSUE TITLE
Ensure that any logo images are secure

### ISSUE THREAD

**Issue by andrew-cunliffe** [DashboardHub/PipelineDashboard#634]
Currently with images being referenced if the link is not secure (https) then it is no longer deemed to be a secure page by a browser and the padlock is lost

### Requirements

**API**
- [ ] Logo validation: url, https only

**UI**
- [ ] Logo validation: url, https only

**Comment by eddiejaoude** [comment]
Thanks for the feedback 👍

**Comment by eddiejaoude** [comment]
Fixed in #634
