### ISSUE TITLE
Add DH badge to README once deployed to prod

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#662]
### Requirements

**API**
- [ ] Task One
- [ ] Task Two

**UI**
- [ ] Task One
- [ ] Task Two

**Comment by sarajaoude** [comment]
<img width="859" alt="screenshot 2018-02-10 10 21 40" src="https://user-images.githubusercontent.com/11989248/36061042-3699f096-0e4c-11e8-95cd-a4ad12cfa47b.png">
