### ISSUE TITLE
Dev environment for local VMs

### ISSUE THREAD

**Issue by chris-moreton** [DashboardHub/PipelineDashboard#69]
Vagrant VMs, or indeed and VMs are not considered development environments by app_dev.php. The web server rewrites all requests in development environments to use the front controller at app_dev.php rather than app.php. However, app_dev.php rejects the request when run in a local VM because it believes it is in a production environment where app_dev.php has been accidentally deployed. We need to allow this use case through within app_dev.php.

**Comment by brettminnie** [comment]
Makes sense, but of a silly limitation in symfony

**Comment by eddiejaoude** [comment]
PR regarding this causing me an issue https://github.com/DashboardHub/PipelineDashboard/issues/71
