### ISSUE TITLE
ENV variable error in dev mode

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#71]
https://github.com/DashboardHub/PipelineDashboard/pull/70 

![screenshot 2015-03-09 21 15 12](https://cloud.githubusercontent.com/assets/624760/6564559/9cab83d6-c6a1-11e4-9235-cb7a4f0c3bc8.png)

**Comment by eddiejaoude** [comment]
Using the built in web server, must specify a ENV variable.

Usually use
```php app/console server:run -vvv```

but need to use
```php app/console server:run -vvv --env=dev```

Not a big deal, but might be a better way to check in the `app_dev.yml`?

**Comment by eddiejaoude** [comment]
PR created with instructions https://github.com/DashboardHub/PipelineDashboard/pull/72

**Comment by eddiejaoude** [comment]
Scrub that, still an issue :cry:

**Comment by eddiejaoude** [comment]
I fixed by suppressing missing value - similar to the same way symfony does it in that file with `@` ... haven't used that in many years, but a `dev` file I guess.

**Comment by brettminnie** [comment]
Maybe do an isset && equals in a condition set

**Comment by eddiejaoude** [comment]
I had something similar, but the symfony guys used the `@` a few lines down (`@$_SERVER['REMOTE_ADDR']`), so i kept it similar.
