### ISSUE TITLE
Mark Environment as red if build/deploy takes longer than 60mins

### ISSUE THREAD

**Issue by chowbertilla** [DashboardHub/PipelineDashboard#745]
If a build/deploy is taking too long, and no complete state has come in, highlight as red

**UI**
- [ ] Environment list
- [ ] Environment view
- [ ] Tooltip to display what is wrong for releases
- [ ] Tooltip to display what is wrong for pings

**Comment by eddiejaoude** [comment]
Closing as using GitHub data and not collecting our own
