### ISSUE TITLE
Team page / section

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#783]
### Requirements

- profile photo
- bio 
- link to GitHub account
- link to LinkedIn
- members
- position
- rate?
Etc

What do you think @chowbertilla @csengep ? Please comment below with your thoughts

**Comment by chowbertilla** [comment]
Happy with all of the above! Will write it all up if we decide to go ahead with this :) @eddiejaoude @csengep

**Comment by csengep** [comment]
Same here! @eddiejaoude @chowbertilla

**Comment by eddiejaoude** [comment]
@csengep Great idea 👍 ❤️
