### ISSUE TITLE
Environments fuse widgets title and chart background color issue

### ISSUE THREAD

**Issue by duskok** [DashboardHub/PipelineDashboard#846]
### Requirements

**UI**
- [ ] The title in environments (the fuse widgets) goes a bit off the top, removing the line-height fixes it
- [ ] The blue colour background on the environment releases chart is a bit difficult to look at, white would be better

**Comment by eddiejaoude** [comment]
Thanks @duskok for the feedback. As we are in the process of removing the template, I am going to close this.
