### ISSUE TITLE
When signing in, once routed to the home page signing button still appears

### ISSUE THREAD

**Issue by brettminnie** [DashboardHub/PipelineDashboard#88]

**Comment by eddiejaoude** [comment]
Really, I don't get that? I will add a Behat test to check that the `login` button disappears once logged in.

This is what I get... https://www.dropbox.com/s/dhki0xvlk99wt2y/dashboardhub-login-video.mov?dl=0

**Comment by brettminnie** [comment]
That big green free sign in with github button, sorry I wasn't clear :)

That is confusing

**Comment by eddiejaoude** [comment]
Ah ok, I completely forgot about that one.

**Comment by brettminnie** [comment]
:D

See, haven't poked it in a while, DFU tests ;)

**Comment by eddiejaoude** [comment]
I updated the Hero box to show `Dashboard list` instead of `login` when a user is logged in. But I put it as part of this PR https://github.com/DashboardHub/PipelineDashboard/pull/90

**Comment by eddiejaoude** [comment]
Not logged in:
![screenshot 2015-03-16 12 43 47](https://cloud.githubusercontent.com/assets/624760/6666216/275408fe-cbda-11e4-8c64-7084feb52103.png)

Logged in:
![screenshot 2015-03-16 12 43 41](https://cloud.githubusercontent.com/assets/624760/6666224/2fcf5b96-cbda-11e4-987d-762550649b27.png)

**Comment by brettminnie** [comment]
There are no heros in agile :)

**Comment by eddiejaoude** [comment]
LOL :+1: 

Here is the commit for reference: https://github.com/DashboardHub/PipelineDashboard/commit/2ed3a3172ea8f54a850fa29b8c47c9b917677b15
