### ISSUE TITLE
Usability: Hints

### ISSUE THREAD

**Issue by brettminnie** [DashboardHub/PipelineDashboard#89]
When adding a new dashboard, please add hints to the text area as to what is actually required

**Comment by eddiejaoude** [comment]
![screenshot 2015-03-16 11 53 40](https://cloud.githubusercontent.com/assets/624760/6665587/1c6b9f58-cbd3-11e4-9895-349f69f912df.png)

PR created, does that help, or more required?

**Comment by brettminnie** [comment]
:+1:

**Comment by eddiejaoude** [comment]
Cool, I will close, there is a PR for you when you get a sec  https://github.com/DashboardHub/PipelineDashboard/pull/91
