### ISSUE TITLE
Token page intro text for what it is about

### ISSUE THREAD

**Issue by sarajaoude** [DashboardHub/PipelineDashboard#890]
### Requirements

Add to the top more info on...

- Manage tokens text
- What are tokens
- Tokens allow you to link your CI with DH to communicate your build / deploy status
- Click on the green button within the list to view example usage of the token

<img width="1407" alt="screenshot 2018-05-22 12 51 03" src="https://user-images.githubusercontent.com/11989248/40360691-d8637214-5dbe-11e8-9df9-3f5804c9a5ac.png">

**Comment by eddiejaoude** [comment]
PR has been merged
