### ISSUE TITLE
Blog post on flexible working and working remotely

### ISSUE THREAD

**Issue by chowbertilla** [DashboardHub/PipelineDashboard#911]
- [x] Devon :D

**Comment by chowbertilla** [comment]
**_Behind the Scenes: Remote Working at DashboardHub_**

I write this blog post on a beautiful summer’s day on a secluded farm in North Devon, surrounded by the smell of fresh lavender and endless fields of cows, horses and buttercups as I code away for a few hours after having done a bit of horse riding, the only things connecting me to the outside world being a car and WiFi. This idyllic scene is perhaps the epitome of just what remote working can do for startups and their employees alike. DashboardHub has, from the beginning, made the decision not to have a physical office, preferring instead for team members to work remotely. Whilst much ink has no doubt already been spilt singing the praises of remote working, I hope here to paint a picture of how they DashboardHub.

**To commute or not to commute… that’s not even a question!**
Although I have not even started my professional career, by way of work placements I have had my fair share of jostling on the tube and finding myself exhausted by the commute when I arrive at the office before I even start the day’s work. By contrast, working at DashboardHub has so far proven to be some of the most efficient learning and working I have done, since, whenever I feel inspiration strike or I have a couple of minutes here and there idling away at a cafe, putting in that extra bit of work is just a matter of opening the lid of my laptop. On particularly lazy days I would even find myself waking up and immediately feeling inspired to code, so I would be full of the energy and momentum to start my day right away even though I might still be in my bed and PJs!

**A diverse team means that everybody works differently**
The team behind DashboardHub is lean but incredibly diverse; we all have very different backgrounds and different ways we work to our full potential. The traditional 9-to-5 simply isn’t always the most optimal for everyone (case in point: me), and, since my family lives in Hong Kong (which is 7-8 hours ahead), I go back to visit a few times every year, which would make a rigid 9-to-5 (on English time) very difficult. The flexibility at DashboardHub means that I am encouraged to work whenever I am at my most productive, whether it is noon, midnight, or some time in between. I really do believe that this leads to a higher and more inspired quality of work within a shorter timeframe: by contrast, the facetime culture that is so pervasive in offices means that employees can be there physically but not mentally. I imagine many cups of tea must have been made in offices to pass the time when one is feeling uninspired, but with DashboardHub I often find myself so engrossed and in the flow that I simply don’t have time for tea!

**Pair programming**
One of the most important learning tools for a budding coder is pair programming (or “pairing”), where you share your screen with another coder and either work together, or have one drive/lead the session and the other one watching, commenting and suggesting improvements. This has proven to be a particularly important tool when I am stuck or am at my wits’ end during debugging. Remote working is particularly conducive to pairing, since all you really need is WiFi/hotspotting and headphones with a mic, and does as good a job as pairing while being physically together with your colleagues in an office.

**Comment by chowbertilla** [comment]
@eddiejaoude Please review :)

**Comment by eddiejaoude** [comment]
@chowbertilla looks great! 👍 

Can I make a suggestion, may be switch the last 2 paragraphs around, because the `A diverse team means that everybody works differently` section is a great way to conclude 🤓

**Comment by chowbertilla** [comment]
Closing this ticket now - can still take the text from this page when needed

**Comment by chowbertilla** [comment]
![whatsapp image 2018-05-27 at 15 37 27 1](https://user-images.githubusercontent.com/21239137/40712729-4d4527e8-63f6-11e8-9f70-dc686e949801.jpeg)

**Comment by chowbertilla** [comment]
![whatsapp image 2018-05-27 at 15 37 27](https://user-images.githubusercontent.com/21239137/40712743-54df8b6a-63f6-11e8-9a58-45c59f7c0863.jpeg)
