### ISSUE TITLE
Blog Post on Hackathon (part 2)

### ISSUE THREAD

**Issue by csengep** [DashboardHub/PipelineDashboard#938]
- create a blog post on Hackathon for non-techies 
- possible future blog posts explaining techie things to non-techies

**Comment by eddiejaoude** [comment]
Could do a 2 part blog post?

Part 1: After helping at the WomenDrivenDevelopment hackathon
Part 2: After participating in a hackathon

**Comment by csengep** [comment]
Sounds good :)

**Comment by eddiejaoude** [comment]
I think this has been completed here https://medium.com/@dashboardhub/women-driven-development-hackathon-2-0-674c3fccbec8
