### ISSUE TITLE
Website video 

### ISSUE THREAD

**Issue by csengep** [DashboardHub/PipelineDashboard#948]
- the video will not go full screen on my computer and screenshots are impossible to see. The smaller fonts might also be too small for some people. 
- on my phone it goes full screen but screenshots still impossible to see. 

**suggestions:**

- fix video to go full screen 
- focusing the screenshots and making them readable should probably wait until the video is re-done if it is decided we do that.

**Comment by sarajaoude** [comment]
Good points, ideally, the plan is to redo the video, there is a ticket for it https://github.com/DashboardHub/PipelineDashboard/issues/935

I will take the content from above and move it to the other ticket and close this one, so there is no confusion of where to add more ideas.
