### ISSUE TITLE
Update screenshots in README to new app design

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/PipelineDashboard#952]
Update these 2 images with the following from the new design:

- Public environment list page screenshot
- Environment view page screenshot

**Comment by chowbertilla** [comment]
<img width="1280" alt="public environment" src="https://user-images.githubusercontent.com/21239137/41191244-6e6e38f6-6be4-11e8-8b7b-1691dfeeb183.png">

**Comment by chowbertilla** [comment]
<img width="1280" alt="releases" src="https://user-images.githubusercontent.com/21239137/41191254-8542894c-6be4-11e8-9ce2-bf9df67fa985.png">
