### ISSUE TITLE
Glossary idea on new app 

### ISSUE THREAD

**Issue by csengep** [DashboardHub/PipelineDashboard#955]
So as the aim is to lower barrier to entry I think these words need to be explained on the help and FAQs page

- **pings**
- **releases**
- **monitors**
- **Beacon**
- **CI**

**Comment by eddiejaoude** [comment]
@chowbertilla we could add this to the `help` section

**Comment by chowbertilla** [comment]
<img width="570" alt="glossary_table" src="https://user-images.githubusercontent.com/21239137/41206045-bc490d0a-6cf5-11e8-8002-1017a40991df.png">
